### PR TITLE
Add APP_ENV as the most prior variable to use

### PR DESCRIPTION
**Pull request by MAKARD**
Currently, there is no way to use the custom BABEL_ENV value, as it's overwritten by some packages, which are required in RN project. For example
https://github.com/facebook/metro/blob/eabdbf3ebfc27dceae9e968f2d151373148b5eba/packages/metro-react-native-babel-transformer/src/index.js#L184

So that, the easiest and convenient way to solve this issue - create a custom isolated env variable, which will have the most priority.

### CODE REVIEW

**Comment by MAKARD** [comment]
Published as https://www.npmjs.com/package/react-native-dotenv-fixed
If this PR will be merged, the package needs to be marked as deprecated.

**Comment by goatandsheep** [comment]
@MAKARD thank you for your PR! I think we should expand on the usage of this though first. You'd have to set it in your CLI when you run? We should show an example. And I don't think we should describe it as choosing which file to use but rather which environment because it's easy to mistake that for meaning path, which will fail if it's located in a separate folder. Most users of this library should not need to be using `APP_ENV`. It should only really be used if there are Babel plugins overwriting it. What do you think?

**Comment by MAKARD** [comment]
Yeah, can we use this particular example?
```JSON
// package.json
{
  "scripts": {
    "start:staging": "APP_ENV=staging npx react-native start",
  }
}
```
```
// available envs
.env.production
.env.development
.env.staging ----> this env will be used
```

As for the usage of an environment instead of a specific file, I guess you're right. Specifying a custom name for the environment may confuse users. Maybe we can use another var name instead of `APP_ENV`, that will clearly tell users of its purposes?

And for babel plugins. I really believe, that most rn developers use metro as a bundler, so we can assume that this is not a specific extra case, but rather common behavior

**Comment by goatandsheep** [comment]
@MAKARD if we can get a test added I'll merge it in! I received some additional comments and thought about it some more and I think this is valuable

**Comment by goatandsheep** [comment]
Also for some reason, i'm struggling to push changes. I'm happy to help but i'm having issues. In the README, I changed line 154 to be:

> 
> 
> ### Experimental feature
> 
> One thing that we've noticed is that metro overwrites the `test` environment variable even if you specify a config so we've added a way to fix this. Make sure to specify the config value as indicated in the [wiki](https://github.com/goatandsheep/react-native-dotenv/wiki/Multi-env-troubleshooting) and make custom configs for alternative builds. However, if you still need this, such as for a `staging` / `test` environment, you can add the `APP_ENV` environment variable in the CLI. For example:
> 
> ```JSON
> // package.json
> {
>   "scripts": {
>     "start:staging": "APP_ENV=staging npx react-native start",
>   }
> }
> ```
> 
> The above example would use the `.env.staging` file. The standard word is `test`, but go nuts.

could you add this to that line?

**Comment by MAKARD** [comment]
@goatandsheep I've added a test case for APP_ENV usage and modify docs as you asked. Happy New Year 🎉

**Review by goatandsheep — APPROVED** [review]

**Pull request merged**
